apiVersion: v1
kind: ConfigMap
metadata:
    name: app-configmap
data:
    redis-service: my-release-redis-master:6379
    redis-host: my-release-redis-master
    port: "8080"
    redis-db: "0"
    redis-port: "6379"
    
