version: '3.7'
services: 
    redis:
      image: "redis:alpine"
      command: ["redis-server", "--appendonly", "yes"]
      volumes: 
        - redis_data:/var/lib/redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - "6379:6379"
      environment: 
        - REDIS_REPLICATION_MODE=master
      container_name: id_service_redis
    app:
      build: .
      image: jakubator/id_service
      depends_on: 
        - redis
      ports: 
        - "8080:8080"
      environment:
          REDIS_URL: redis:6379
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          PORT: ${PORT}
          REDIS_HOST: ${REDIS_HOST}
          REDIS_PORT: ${REDIS_PORT}
          REDIS_DB: ${REDIS_DB}
      container_name: id_service

volumes: 
  redis_data: 
